# Generated by Django 2.1.1 on 2018-09-06 18:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_day', models.DateField(db_index=True, default=datetime.date(2018, 9, 6))),
                ('timestamp', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('is_validated', models.BooleanField(default=False)),
                ('validate_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailystudy_validator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begining', models.FloatField()),
                ('end', models.FloatField()),
                ('amount', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Course')),
                ('studies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_study', to='daily_study.DailyStudy')),
            ],
        ),
    ]
