# Generated by Django 2.1.1 on 2018-09-09 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_study', '0002_auto_20180906_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudy',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailystudy',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
