# Generated by Django 2.1.1 on 2018-09-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_study', '0003_auto_20180909_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='studies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='daily_study.DailyStudy'),
        ),
    ]
