# Generated by Django 2.1.1 on 2018-09-10 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily_study', '0004_auto_20180910_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudy',
            name='created_day',
            field=models.DateField(db_index=True, default=datetime.datetime(2018, 9, 10, 16, 29, 25, 810433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailystudy',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 16, 29, 25, 810470, tzinfo=utc)),
        ),
    ]
