# Generated by Django 2.1.1 on 2018-09-10 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_study', '0005_auto_20180910_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudy',
            name='created_day',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailystudy',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
