# Generated by Django 2.1.8 on 2019-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('importance', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-importance',),
            },
        ),
        migrations.CreateModel(
            name='CourseGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(related_name='groups', to='course.Course')),
            ],
        ),
    ]
