# Generated by Django 2.1.1 on 2018-10-20 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181018_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='executives',
            field=models.ManyToManyField(blank=True, related_name='area_executive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classroom_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='region_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
