version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3
    steps:
      - checkout
      - deploy:
          name: disgem
          command: ssh -o "StrictHostKeyChecking no" ubuntu@ec2-18-185-137-160.eu-central-1.compute.amazonaws.com "cd ~/StudentTrack2; git pull;"
