# Generated by Django 2.1.1 on 2018-10-10 14:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180906_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Format hatası. Telefon numarası şu formatta olmalı:'05515524294'", regex='^(05)[0-9][0-9] ([0-9]){3} ([0-9]){2} ([0-9]){2}$')]),
        ),
    ]
