# Generated by Django 2.1.1 on 2018-10-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181010_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_joined',
            new_name='joined_date',
        ),
    ]
