# Generated by Django 2.1.1 on 2018-10-12 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181010_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Format hatası. Telefon numarası şu formatta olmalı:'05515524294'", regex='^(05)[0-9][0-9]([0-9]){7}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='related_area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Area'),
        ),
    ]
