# Generated by Django 2.1.1 on 2018-10-16 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181013_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='executives',
            field=models.ManyToManyField(blank=True, related_name='area_executives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classroom_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='region_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
