# Generated by Django 2.1.1 on 2018-10-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='courses',
            field=models.ManyToManyField(related_name='groups', to='base.Course'),
        ),
    ]
