
version: '3'

services:
  # database containers, one for each db
  db:
    image: postgres:10.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - config/db
    ports:
      - 5432:5432

  redis:
    image: redis:4.0-alpine

  # web container, with django + gunicorn
  web:
    restart: always
    build:
        context: ../
        dockerfile: deploy/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - ..:/opt/services/student/src
      - static:/opt/services/student/src/static
      - media:/opt/services/student/src/media

    depends_on:
      - db
      - redis

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.14
    ports:
      - 80:80
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - static:/opt/services/student/src/static
      - media:/opt/services/student/src/media

    depends_on:
      - web

volumes:
  db:
  static:
  media: