# Generated by Django 2.1.1 on 2018-09-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField()),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UserSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validator_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_validator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='syllabus.Syllabus'),
        ),
        migrations.AlterUniqueTogether(
            name='usersyllabus',
            unique_together={('content', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('course', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('week', 'syllabus')},
        ),
    ]
