# Generated by Django 2.1.1 on 2018-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20180907_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
