# Generated by Django 2.1.1 on 2018-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_auto_20180907_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ('course', 'level')},
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.TextField(),
        ),
    ]
