# Generated by Django 2.1.1 on 2018-09-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_remove_content_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='name',
        ),
    ]
