# Generated by Django 2.1.1 on 2018-09-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_auto_20180918_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersyllabus',
            old_name='status',
            new_name='is_validated',
        ),
    ]
