# Generated by Django 2.1.1 on 2018-09-22 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_auto_20180920_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersyllabus',
            name='validator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_validator_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
