# Generated by Django 2.1.3 on 2018-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'İl Vakfı'), (2, 'İlçe Vakfı'), (4, 'Kat Vakfı'), (8, 'Talebe')], null=True),
        ),
    ]
