# Generated by Django 2.1.2 on 2018-11-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('week', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('syllabus', 'week', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'ordering': ('level', 'course'),
            },
        ),
        migrations.CreateModel(
            name='UserSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('content', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='syllabus.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validator_user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_validator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='syllabus.Syllabus'),
        ),
        migrations.AlterUniqueTogether(
            name='usersyllabus',
            unique_together={('content', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('course', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('week', 'syllabus')},
        ),
    ]
